BrowserUtility and ExcelUtility added. Testing pending
ResearchStuff/ProjectOne pull request #1
Opened 2019-12-25 11:21 UTC by DISHANTB

BrowserUtility and ExcelUtility added. Testing pending.

2019-12-25 12:07 UTC, ResearchStuff requested changes
Some Comments added and those needs to be fixed. another round of review will be held afterward

2019-12-25 12:07 UTC, ResearchStuff commented on src/main/java/com/ProjectOne/ProjectOne/App.java
> +/**
No Hello world program is required in the project

2019-12-25 12:07 UTC, ResearchStuff commented on src/main/java/com/ProjectOne/ProjectOne/Utilities/BrowserFactory.java
> +		}
Make sure driver exe are present at the appropriate location.

2019-12-29 07:03 UTC, DISHANTB commented on src/main/java/com/ProjectOne/ProjectOne/Utilities/BrowserFactory.java
> +		}
all exe files are present in Driver folder

2019-12-29 07:06 UTC, merged